export const ADD_DISH_REQUEST = 'ADD_DISH_REQUEST';
export const ADD_DISH_SUCCESS = 'ADD_DISH_SUCCESS';
export const ADD_DISH_FAILURE = 'ADD_DISH_FAILURE';

export const GET_DISH_REQUEST = 'GET_DISH_REQUEST';
export const GET_DISH_SUCCESS = 'GET_DISH_SUCCESS';
export const GET_DISH_FAILURE = 'GET_DISH_FAILURE';

export const DELETE_DISH_REQUEST = 'DELETE_DISH_REQUEST';
export const DELETE_DISH_SUCCESS = 'DELETE_DISH_SUCCESS';
export const DELETE_DISH_FAILURE = 'DELETE_DISH_FAILURE';
