export const ADD_DISH_REQUEST = 'ADD_DISH_REQUEST';
export const ADD_DISH_SUCCESS = 'ADD_DISH_SUCCESS';
export const ADD_DISH_FAILURE = 'ADD_DISH_FAILURE';

export const GET_ALL_DISH_REQUEST = 'GET_ALL_DISH_REQUEST';
export const GET_ALL_DISH_SUCCESS = 'GET_ALL_DISH_SUCCESS';
export const GET_ALL_DISH_FAILURE = 'GET_ALL_DISH_FAILURE';
