export const GET_ALL_RESTAURANT_REQUEST = 'GET_ALL_RESTAURANT_REQUEST';
export const GET_ALL_RESTAURANT_SUCCESS = 'GET_ALL_RESTAURANT_SUCCESS';
export const GET_ALL_RESTAURANT_FAILURE = 'FET_ALL_RESTAURANT_FAILURE';
